"""empty message

Revision ID: bbb430462d0c
Revises: 0869f5facc79
Create Date: 2020-06-03 16:30:37.990335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb430462d0c'
down_revision = '0869f5facc79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roll')
    # ### end Alembic commands ###
